# Header
menu:
  Home: /
  My Works: /works
  About: /about
  #Tags: /tags

rss: /atom.xml

# User Info
user_name: Roto Works
# user_avatar: https://cdn2.iconfinder.com/data/icons/rcons-user/32/male-shadow-circle-512.png
user_avatar: ./images/me.jpg
user_location: Japan
user_description: "フリーランスエンジニア"
user_contact: 5831hirotomo@gmail.com
user_introduction: "iOSエンジニア"

github_username: roto5831
twitter_username: 5831hirotomo
weibo_username:
zhihu_username:
facebook_username: hiro.kobayashi.94
linkedin_username:

# Content
excerpt_link: Read More
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# 评论系统
# 不要用别人的 uid, 自己去注册一个吧
use_livere: true
livere_uid: MTAyMC8yOTE4Ni81NzUz

use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

# Miscellaneous
google_analytics:
favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:

# Highlight code
# do ensure u have closed all the highlight choices in ur root _config.yml
# currently we provided 6 choices based on highlight script
# highlight_default, highlight_light, highlight_github, highlight_rainbow, highlight_vs, highlight_atom
block_highlight: highlight_rainbow
